# telegraf metrics setting 
wireless:
  ## Sets 'proc' directory path
  ## If not specified, then default is /proc
  host_proc: /proc



ping:
    ## Hosts to send ping packets to.
  urls: google.com

  ## Method used for sending pings, can be either "exec" or "native".  When set
  ## to "exec" the systems ping command will be executed.  When set to "native"
  ## the plugin will send pings directly.
  ##
  ## While the default is "exec" for backwards compatibility, new deployments
  ## are encouraged to use the "native" method for improved compatibility and
  ## performance.
  method: native

  ## Number of ping packets to send per interval.  Corresponds to the "-c"
  ## option of the ping command.
  count: 1

  ## Time to wait between sending ping packets in seconds.  Operates like the
  ## "-i" option of the ping command.
  ping_interval: 1.0

  ## If set, the time to wait for a ping response in seconds.  Operates like
  ## the "-W" option of the ping command.
  timeout: 1.0

  ## If set, the total ping deadline, in seconds.  Operates like the -w option
  ## of the ping command.
  deadline: 10

  ## Specify the ping executable binary.
  binary: ping

  ## Number of data bytes to be sent. Corresponds to the "-s"
  ## option of the ping command. This only works with the native method.
  size: 56



intel_powerstat:
  cpu_metrics: '["cpu_frequency, cpu_temperature"]'



file:
      ## Files to write to, "stdout" is a specially handled file.
  files: '["stdout"]'