---
# check is submodules are not empty
- hosts: server
  become_user: "{{ ansible_user }}"
  become: yes
  gather_facts: yes
  roles:
    - {role: setup/command-center/install-docker, become_user: root}
    - {role: setup/command-center/install-minikube, become_user: root }
...



