---

- hosts: raspberry
  gather_facts: no
  become_user: "{{ ansible_user }}"
  vars:
    skip_setup: true 
  roles:
    - {role: rpi/setup, when: skip_setup == false}
    - {role: rpi/deploy-pyWeater}
...