---
- name: create git directory
  file:
    path: "/home/{{ ansible_user }}/git"
    state: directory

- name: pull rpi git repos
  git:
    repo: "{{ git_repos.pyweather.url }}"
    dest: "{{ git_repos.pyweather.dir }}"
  when: ansible_host == "pizero"

- name: end play for raspberry pi
  meta: end_host
  when: ansible_host == "pizero"

- name: pull git repos into git folder
  git:
    repo: "{{ item.value.url }}"
    dest: "{{ item.value.dir }}"
    clone: yes
  loop: "{{ lookup('dict', git_repos) }}"
  when: item.value.dir != git_repos.telegraf.dir
...