---
run_apt_update_upgrade: yes
dell_apt_packages:
    - python3.9
    - python3-pip  
    - wget
    - ca-certificates
    - curl
    - lsb-release
    - gpg
    - apt-transport-https
    - ca-certificates 
    - gnupg
    - zip
    - gcc-multilib
...