---
- name: install rpi zero packages
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: "{{ run_apt_update_upgrade }}"
  when: ansible_facts['os_family']|lower == 'debian'


- name: install python packages
  pip:
    name: "{{ python_packages }}"
...