---

- name: create pi-hole directory
  file:
    path: ~/pi-hole
    state: directory

- name: download pi-hole instalation script
  get_url:
    url: https://install.pi-hole.net
    dest: ~/pi-hole/basic-install.sh
    mode: u+x

...
