- name: check if gcloud is installed
  shell: "{{ gcloud_path }}/google-cloud-sdk/bin/gcloud"
  register: cmd
  ignore_errors: True

- name:  install gcloud
  become: yes
  become_user: root
  block:
    - name: get gcloud.tar.gz archive
      get_url: 
        url: "{{ gcloud_tar_url  }}"
        dest: "{{ gcloud_tar_path }}"
        mode: "0644"

    - name: Extract gcloud.tar.gz into /tmp/gcloud
      unarchive:
        src: "{{ gcloud_tar_path }}"
        dest: "{{ gcloud_path }}"
        remote_src: yes

    - name: install gcloud
      shell: "{{ gcloud_path }}/google-cloud-sdk/install.sh  --quiet"
    

    - name: validate instalation
      shell: "{{ gcloud_path }}/google-cloud-sdk/bin/gcloud"
  when: cmd.rc == 127